name: Build

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        run: ./gradlew build

      - name: Upload Fabric jar
        uses: actions/upload-artifact@v4
        with:
          name: fabric-jar
          path: fabric/build/libs/*.jar
          if-no-files-found: warn

      - name: Upload Forge jar
        uses: actions/upload-artifact@v4
        with:
          name: forge-jar
          path: forge/build/libs/*.jar
          if-no-files-found: warn
